//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodLesZ.Tools.WebScraper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodLesZ.Tools.WebScraper.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid file name for auto saving data.
        /// </summary>
        internal static string AutoSaveInvalidFileName {
            get {
                return ResourceManager.GetString("AutoSaveInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid value for record count for auto saving data.
        /// </summary>
        internal static string AutoSaveInvalidRowCount {
            get {
                return ResourceManager.GetString("AutoSaveInvalidRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Web Page . . .
        /// </summary>
        internal static string BrowserStateLoading {
            get {
                return ResourceManager.GetString("BrowserStateLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready  . ..
        /// </summary>
        internal static string BrowserStateReady {
            get {
                return ResourceManager.GetString("BrowserStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string BrowserTab {
            get {
                return ResourceManager.GetString("BrowserTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        internal static string CategoryColumnName {
            get {
                return ResourceManager.GetString("CategoryColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 links (categories) are supported in Evaluation Version.
        /// </summary>
        internal static string CatEvalLimitMsg {
            get {
                return ResourceManager.GetString("CatEvalLimitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to database.
        /// </summary>
        internal static string DbConnFailed {
            get {
                return ResourceManager.GetString("DbConnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create/connect to database.
        /// </summary>
        internal static string DbCreateFailed {
            get {
                return ResourceManager.GetString("DbCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to edit task.
        /// </summary>
        internal static string EditFailed {
            get {
                return ResourceManager.GetString("EditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the configuration !.
        /// </summary>
        internal static string ErrorLoadingConf {
            get {
                return ResourceManager.GetString("ErrorLoadingConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates . ..
        /// </summary>
        internal static string ErrorUpdateChk {
            get {
                return ResourceManager.GetString("ErrorUpdateChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days remaning for evaluation.
        /// </summary>
        internal static string EvalDays {
            get {
                return ResourceManager.GetString("EvalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available in evaluation version.
        /// </summary>
        internal static string EvalLimitation {
            get {
                return ResourceManager.GetString("EvalLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 keywords are supported in Evaluation Version.
        /// </summary>
        internal static string EvalLimitMsg {
            get {
                return ResourceManager.GetString("EvalLimitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 pages of data can be mined in evaluation mode. To mine more than 2 pages of data, please purchase WebScraper !.
        /// </summary>
        internal static string EvalPageLimit {
            get {
                return ResourceManager.GetString("EvalPageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export data to database.
        /// </summary>
        internal static string ExportDbFailed {
            get {
                return ResourceManager.GetString("ExportDbFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields (database address, database name, table name).
        /// </summary>
        internal static string ExportDbFieldWarning {
            get {
                return ResourceManager.GetString("ExportDbFieldWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid user name and password.
        /// </summary>
        internal static string ExportDbLoginWarning {
            get {
                return ResourceManager.GetString("ExportDbLoginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Database finished successfully.
        /// </summary>
        internal static string ExportDbSuccess {
            get {
                return ResourceManager.GetString("ExportDbSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string Exported {
            get {
                return ResourceManager.GetString("Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting . ..
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a directory where captured files will be saved.
        /// </summary>
        internal static string FileDirBrowse {
            get {
                return ResourceManager.GetString("FileDirBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file already exists. Would you like to append the mined data to the existing file ? Click &apos;Yes&apos; to append, &apos;No&apos; to overwrite..
        /// </summary>
        internal static string FileExistsWarning {
            get {
                return ResourceManager.GetString("FileExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory where captured images will be saved. Cancel to capture image URLs instead..
        /// </summary>
        internal static string ImageDirBrowse {
            get {
                return ResourceManager.GetString("ImageDirBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid values for all input fields.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid value for AJAX Load Wait Time.
        /// </summary>
        internal static string InvalidAjaxLoadTimeout {
            get {
                return ResourceManager.GetString("InvalidAjaxLoadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of WebScraper cannot be unlocked using the selected license file !.
        /// </summary>
        internal static string InvalidLicenseFile {
            get {
                return ResourceManager.GetString("InvalidLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid values for miner pause interval and time.
        /// </summary>
        internal static string InvalidMinerPauseParams {
            get {
                return ResourceManager.GetString("InvalidMinerPauseParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid value for Page Load Timeout.
        /// </summary>
        internal static string InvalidPageLoadTimeout {
            get {
                return ResourceManager.GetString("InvalidPageLoadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL !.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading last mined page . . ..
        /// </summary>
        internal static string LoadingLastMinedPage {
            get {
                return ResourceManager.GetString("LoadingLastMinedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Preview . . ..
        /// </summary>
        internal static string LoadingPreview {
            get {
                return ResourceManager.GetString("LoadingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data . . .
        /// </summary>
        internal static string MineAutoSavingData {
            get {
                return ResourceManager.GetString("MineAutoSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MineFormReady {
            get {
                return ResourceManager.GetString("MineFormReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining . ..
        /// </summary>
        internal static string MineFormStart {
            get {
                return ResourceManager.GetString("MineFormStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string MineFormStop {
            get {
                return ResourceManager.GetString("MineFormStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused (Auto Pause Injection).
        /// </summary>
        internal static string MineInjectPaused {
            get {
                return ResourceManager.GetString("MineInjectPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Page #.
        /// </summary>
        internal static string MineLoadingPage {
            get {
                return ResourceManager.GetString("MineLoadingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Live ! Continuing Mining . . ..
        /// </summary>
        internal static string MineNetworkBackLive {
            get {
                return ResourceManager.GetString("MineNetworkBackLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Lost ! Waiting for connection . . . .
        /// </summary>
        internal static string MineNetworkLost {
            get {
                return ResourceManager.GetString("MineNetworkLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string MinePaused {
            get {
                return ResourceManager.GetString("MinePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing . . .
        /// </summary>
        internal static string MinePausing {
            get {
                return ResourceManager.GetString("MinePausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Page #.
        /// </summary>
        internal static string MineProgress {
            get {
                return ResourceManager.GetString("MineProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing duplicate records . ..
        /// </summary>
        internal static string MineRemovingDuplicates {
            get {
                return ResourceManager.GetString("MineRemovingDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the name &apos;{0}&apos; already exists !.
        /// </summary>
        internal static string MsgDuplicateFieldName {
            get {
                return ResourceManager.GetString("MsgDuplicateFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the page loads completely !.
        /// </summary>
        internal static string MsgPageLoading {
            get {
                return ResourceManager.GetString("MsgPageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update of WebScraper is available. Would you like to download it now ?.
        /// </summary>
        internal static string NewUpdateAvailable {
            get {
                return ResourceManager.GetString("NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available, but your current license has expired. Would you like to purchase the latest version ?.
        /// </summary>
        internal static string NewUpdatePurchase {
            get {
                return ResourceManager.GetString("NewUpdatePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available, but you should upgrade your license to unlock it. Would you like to upgrade to the latest version ?.
        /// </summary>
        internal static string NewUpdateUpgrade {
            get {
                return ResourceManager.GetString("NewUpdateUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid WebScraper configuration is currently opened . . .
        /// </summary>
        internal static string NoConfigOpened {
            get {
                return ResourceManager.GetString("NoConfigOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates are available.
        /// </summary>
        internal static string NoNewUpdates {
            get {
                return ResourceManager.GetString("NoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebScraper.
        /// </summary>
        internal static string PgmName {
            get {
                return ResourceManager.GetString("PgmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebScraper Evaluation.
        /// </summary>
        internal static string PgmNameEval {
            get {
                return ResourceManager.GetString("PgmNameEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like the page has a large number of records. Should WebScraper generate the complete preview ? (Generating complete preview is not required) .
        /// </summary>
        internal static string ProceedPreviewGeneration {
            get {
                return ResourceManager.GetString("ProceedPreviewGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid proxy address.
        /// </summary>
        internal static string ProxyIncorrectAddress {
            get {
                return ResourceManager.GetString("ProxyIncorrectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid username and password.
        /// </summary>
        internal static string ProxyIncorrectAuth {
            get {
                return ResourceManager.GetString("ProxyIncorrectAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid time interval for rotating proxy addresses.
        /// </summary>
        internal static string ProxyIncorrectInterval {
            get {
                return ResourceManager.GetString("ProxyIncorrectInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid port number.
        /// </summary>
        internal static string ProxyIncorrectPort {
            get {
                return ResourceManager.GetString("ProxyIncorrectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records mined.
        /// </summary>
        internal static string RecordsMined {
            get {
                return ResourceManager.GetString("RecordsMined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations ! You have successfully registered WebScraper.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is registered to : .
        /// </summary>
        internal static string RegistrationName {
            get {
                return ResourceManager.GetString("RegistrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to resume mining from where it stopped previously (Click Yes) ? Click No to clear the data table and restart mining..
        /// </summary>
        internal static string ResumeAbortedMining {
            get {
                return ResourceManager.GetString("ResumeAbortedMining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to schedule task.
        /// </summary>
        internal static string ScheduleFailed {
            get {
                return ResourceManager.GetString("ScheduleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select (place the cursor) in the input field (text box) of the web page first..
        /// </summary>
        internal static string SelectInputField {
            get {
                return ResourceManager.GetString("SelectInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The browser will now navigate following the first link. When you reach the page containing the data to be scraped click &apos;Start Config&apos; toolbar button. Your configuration will be automatically repeated for all links in the list..
        /// </summary>
        internal static string SelectSectionsConfMessage {
            get {
                return ResourceManager.GetString("SelectSectionsConfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebScraper was unable to parse the list of links !.
        /// </summary>
        internal static string SelectSectionsErrorMessage {
            get {
                return ResourceManager.GetString("SelectSectionsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the first link in the list.
        /// </summary>
        internal static string SelectSectionsMessage {
            get {
                return ResourceManager.GetString("SelectSectionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the links one by one. Click on empty space when finished. .
        /// </summary>
        internal static string SelectSectionsMessage2 {
            get {
                return ResourceManager.GetString("SelectSectionsMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a task.
        /// </summary>
        internal static string SelectTask {
            get {
                return ResourceManager.GetString("SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to select more categories ?.
        /// </summary>
        internal static string SelMoreCategoriesMessage {
            get {
                return ResourceManager.GetString("SelMoreCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create table.
        /// </summary>
        internal static string TableCreateFailed {
            get {
                return ResourceManager.GetString("TableCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid column name.
        /// </summary>
        internal static string TagColNameError {
            get {
                return ResourceManager.GetString("TagColNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your free upgrade period has expired. Would you like to purchase an upgrade to the latest version of WebScraper ?.
        /// </summary>
        internal static string UpgradeMsg {
            get {
                return ResourceManager.GetString("UpgradeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free update period of your current license has expired. Would you like to purchase the license upgrade ?.
        /// </summary>
        internal static string UpgradePrompt {
            get {
                return ResourceManager.GetString("UpgradePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 URLs are supported in Evaluation Version.
        /// </summary>
        internal static string UrlEvalLimitMsg {
            get {
                return ResourceManager.GetString("UrlEvalLimitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Data, Please Wait . . ..
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
